### DISCUSSION TITLE
docker compose not working

### DISCUSSION THREAD

**Discussion by oscar6echo** [fief-dev/fief#210] [Q&A] [answered]
I spotted 2 problems with the [docker compose](https://docs.fief.dev/self-hosting/deployment/docker-compose/) deployment in the docs:
Point 1 is solved, but point 2 is blocking.

1/
As I did not want to expose it on port 80 I changed it to 8000.  
I needed to substitute `expose` by `ports` to work:

```yml
services:
  fief-server:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-server --port 8000

    # does not work:
    # expose:
    #   - "8000"

    # works:
    ports:
      - "8000:8000"

    env_file:
      - .env
      - 
```

2/
After successfully logging as the fief_main_user I see:

![image](https://github.com/fief-dev/fief/assets/2219383/7470fe89-0a03-42f1-b36e-9be47cb3b419)

Then I navitagate to `http://localhost:8000/admin/` and see the following "Unknown client error".  
Note that the exact same process with the "quickstart docker run" with the same `.env` parameters (see below) works (i.e. shows the admin screen) :

![image](https://github.com/fief-dev/fief/assets/2219383/0234d9de-b49a-4b84-b32a-2e9eea3a2415)

The docker compose `.env` file is:

```env
# Reference: https://docs.fief.dev/self-hosting/environment-variables/

# these params were created with the quickstart procedure
SECRET=XXX
FIEF_CLIENT_ID=XXX
FIEF_CLIENT_SECRET=XXX
ENCRYPTION_KEY=XXX=

PORT=8000
ROOT_DOMAIN=localhost:8000
FIEF_DOMAIN=localhost:8000
FIEF_MAIN_USER_EMAIL=oscar22@gmail.com
FIEF_MAIN_USER_PASSWORD=Toto*/12345


# Read more: https://docs.fief.dev/self-hosting/deployment/setup-database/
DATABASE_TYPE=POSTGRESQL
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USERNAME=fief
DATABASE_PASSWORD=fief
DATABASE_NAME=fief

REDIS_URL=redis://redis:6379
```

The quickstart docker run env file is:

```env
SECRET=XXX
FIEF_CLIENT_ID=XXX
FIEF_CLIENT_SECRET=XXX
ENCRYPTION_KEY=XXX=
PORT=8000
ROOT_DOMAIN=localhost:8000
FIEF_DOMAIN=localhost:8000
FIEF_MAIN_USER_EMAIL=oscar22@gmail.com
FIEF_MAIN_USER_PASSWORD=Toto*/12345

CSRF_COOKIE_SECURE=False
SESSION_DATA_COOKIE_SECURE=False
USER_LOCALE_COOKIE_SECURE=False
LOGIN_HINT_COOKIE_SECURE=False
LOGIN_SESSION_COOKIE_SECURE=False
REGISTRATION_SESSION_COOKIE_SECURE=False
SESSION_COOKIE_SECURE=False
FIEF_ADMIN_SESSION_COOKIE_SECURE=False
```

What is the reason ?  
Pls advise.
