### DISCUSSION TITLE
Tutorial: How to use Fief with Docker Compose along with other services

### DISCUSSION THREAD

**Discussion by gabrielcnegre** [fief-dev/fief#282] [Show and tell]
Hey everyone,

I've been in the development field for several years, but surprisingly, this is my first contribution to a GitHub thread. I apologize if there are any procedural errors or if this isn't the optimal place to share this solution.

First and foremost, I'd like to express my gratitude for this project. I genuinely hope for its immense success.

Recently, I've been experimenting with Fief in one of my projects. I noticed there's been a significant amount of discussion on integrating Fief with Compose. The primary challenges revolve around how the Fief client authenticates in conjunction with Docker networking. In short, the keys and the openid configuration returned by the server are associated with the host. However, the internal service's API call host isn't identical to the host accessed from localhost (e.g., accessing a FastAPI service via a browser).

Some have suggested using ngrok as a solution, but I encountered challenges. The jwks, for instance, returns URI`s to http, which the client struggles to handle (since it gets redirected). Additionally, ngrok introduces other complications, like with OpenAPI docs. (mixed http/https sources)

The other idea was to change the docker networking to host, but this still did not work, since the origin host that calls the client is different that the one calling the API. 

I've found a working solution: Traefik!

Since Traefik serves as a reverse proxy it allows you to configure routers to localhost subdomains. Subsequently, these subdomains can be directed to your machine's localhost (labeled "host-gateway") within the services, ensuring consistent hostnames.

```yaml
x-fief:
  &fief
  environment:
    - SECRET=${FIEF_SECRET}
    - FIEF_CLIENT_ID
    - FIEF_CLIENT_SECRET
    - ENCRYPTION_KEY=${FIEF_ENCRYPTION_KEY}
    - PORT=8000
    - ROOT_DOMAIN=${FIEF_ROOT_DOMAIN}
    - FIEF_DOMAIN=${FIEF_DOMAIN}
    - FIEF_MAIN_USER_EMAIL
    - FIEF_MAIN_USER_PASSWORD
    - DATABASE_TYPE=POSTGRESQL
    - DATABASE_HOST=${POSTGRES_HOST}
    - DATABASE_PORT=${POSTGRES_PORT}
    - DATABASE_USERNAME=${FIEF_POSTGRES_USER}
    - DATABASE_PASSWORD=${FIEF_POSTGRES_PASSWORD}
    - DATABASE_NAME=${FIEF_POSTGRES_DB}
    - REDIS_URL=redis://${REDIS_USER}:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
  depends_on:
    - postgres
    - redis
    
services:
  
  #... your other services ...

   traefik: # HERE
      image: traefik:v2.4
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - 80:80
        - 8080:8080
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
       
   api:
      <<: *backend
      command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
      extra_hosts: # HERE 
        - "fief.localhost:host-gateway"                                                                     
      labels: # HERE
        - "traefik.enable=true" 
        - "traefik.http.routers.api.rule=Host(`api.localhost`)"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
      expose: # HERE
        - 8000
      
  fief-server:
    <<: *fief
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-server --port 8000
    labels: # HERE
      - "traefik.enable=true"
      - "traefik.http.routers.fief.rule=Host(`fief.localhost`)"
      - "traefik.http.routers.fief.entrypoints=web"
      - "traefik.http.services.fief.loadbalancer.server.port=8000"
    expose: # HERE
      - 8000
      
  fief-worker:
      <<: *fief
      image: ghcr.io/fief-dev/fief:latest
      command: fief run-worker -p 1 -t 1
```

.env

```
FIEF_SECRET=XXX
FIEF_CLIENT_ID=XXX
FIEF_CLIENT_SECRET=XXX
FIEF_ENCRYPTION_KEY=XXX
FIEF_PORT=8000
FIEF_ROOT_DOMAIN=localhost
FIEF_DOMAIN=fief.localhost
FIEF_MAIN_USER_EMAIL=your@email.com
FIEF_MAIN_USER_PASSWORD=XXX
FIEF_SERVER_URL=http://fief.localhost
```

If you want to use FastAPI:

```python
from typing import Annotated

from fastapi import Depends
from fastapi.security import OAuth2AuthorizationCodeBearer
from fief_client import FiefAccessTokenInfo, FiefAsync
from fief_client.integrations.fastapi import FiefAuth

from settings import settings

fief = FiefAsync(settings.fief_server_url, settings.fief_client_id, settings.fief_client_secret)

oauth2 = OAuth2AuthorizationCodeBearer(
    f"{settings.fief_server_url}/authorize",
    f"{settings.fief_server_url}/api/token",
    scopes={"openid": "openid", "offline_access": "offline_access"},
    auto_error=False,
)

auth = FiefAuth(fief, oauth2)

AuthenticatedUser = Annotated[FiefAccessTokenInfo, Depends(auth.authenticated())]
```

Now you can access Fief at "fief.localhost" and your api at "api.localhost".

Hope it helps! (Please feel free to ask anything or offer suggestions / improvements)
