### DISCUSSION TITLE
Simple Python Example Using Dockerized Fief Services

### DISCUSSION THREAD

**Discussion by ScottFred** [fief-dev/fief#299] [Q&A] [answered]
Using [the Tutorial from Gabriel](https://github.com/orgs/fief-dev/discussions/282) which adds Traefik as a reverse proxy in front of Fief, I was able to get Fief up and running, but  it required a lot of changes on my end to get his example to start a Fief Server and the other processes.  So, I thought I would document what changes I made here and ask questions to help me get unstuck.  (I'm running locally on a Mac).  

Once I got my local version of Fief up and running, I wanted to use [the simple Getting Started Python example](https://docs.fief.dev/integrate/python/) to manually verify that the networking appeared to be working.  And that's where I keep getting stuck... the Python Getting Started doesn't work using a local version of Fief.  I've tried just pure Docker Networking, I tried the Ngrok suggestion that @frankie567 suggested.  But, none of these have worked, so I thought I would try Gabriel's Traefik setup.

As an alternative, I created a Fief Cloud account and was able to quickly get it to work with Fief Cloud.  So, I know that simple code works.  More on that after I describe what I created here with Traefik as a reverse proxy.

Here are the files I created to get Fief running (fief-server, fief-worker, postgres, redis, traefik):

```
# docker-compose.yml

x-fief:
  &fief-environment
  environment:
    - SECRET=${FIEF_SECRET}
    - FIEF_CLIENT_ID=${FIEF_CLIENT_ID}
    - FIEF_CLIENT_SECRET=${FIEF_CLIENT_SECRET}
    - ENCRYPTION_KEY=${FIEF_ENCRYPTION_KEY}
    - PORT=${PORT} # Q? Where is this used?
    - ROOT_DOMAIN=${FIEF_ROOT_DOMAIN}
    - FIEF_DOMAIN=${FIEF_DOMAIN}
    - FIEF_MAIN_USER_EMAIL=${FIEF_MAIN_USER_EMAIL}
    - FIEF_MAIN_USER_PASSWORD=${FIEF_MAIN_USER_PASSWORD}
    - DATABASE_TYPE=${DATABASE_TYPE}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_USERNAME=${DATABASE_USERNAME}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}
    - REDIS_URL=${REDIS_URL}
  depends_on:
    - db
    - redis

services:
   traefik:
      image: traefik:v2.4
      container_name: fief-traefik
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - 80:80
        - 8080:8080  # Q? How is this being used?
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

   db:
      container_name: fief-db
      image: postgres:16.1-alpine
      ports:
        - 5432:5432
      env_file: # technically not necessary because default .env is used
        - .env
      volumes:
        - fief-postgres-data:/var/lib/postgresql/data

   redis:
      container_name: fief-redis
      image: redis:alpine
      command: redis-server --save 60 1 --loglevel warning
      volumes:
        - fief-redis-data:/data
       
   server:
      <<: *fief-environment
      container_name: fief-server
      image: ghcr.io/fief-dev/fief:0.27.0
      command: fief run-server --port 8000
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fief.rule=Host(`fief.localhost`)"
        - "traefik.http.routers.fief.entrypoints=web"
        - "traefik.http.services.fief.loadbalancer.server.port=8000"
      expose:
        - 8000

   worker:
      <<: *fief-environment
      container_name: fief-worker
      image: ghcr.io/fief-dev/fief:0.27.0
      command: fief run-worker -p 1 -t 1

volumes:
  fief-redis-data:
  fief-postgres-data:
```

```
# .env

# Reference: https://docs.fief.dev/self-hosting/environment-variables/
# Fief Secrets
FIEF_SECRET=xxxxx
FIEF_CLIENT_ID=yyyy
FIEF_CLIENT_SECRET=zzzzz
FIEF_ENCRYPTION_KEY=aaaaa
PORT=8000
FIEF_ROOT_DOMAIN=localhost
FIEF_DOMAIN=fief.localhost
FIEF_MAIN_USER_EMAIL=scott@<email>
FIEF_MAIN_USER_PASSWORD=bbbbbb
FIEF_SERVER_URL=http://fief.localhost

# Read more: https://docs.fief.dev/self-hosting/deployment/setup-database/
DATABASE_TYPE=POSTGRESQL
DATABASE_HOST=fief-db
DATABASE_PORT=5432
DATABASE_USERNAME=fief
DATABASE_PASSWORD=cccccc
DATABASE_NAME=fief

REDIS_URL=redis://fief-redis:6379
```

Now, to get to [the Getting Started Python example](https://docs.fief.dev/integrate/python/).  First, I'm running it in a Docker container.  So, I start the Docker container and attach it to the Fief Network that is started with the Docker Compose file, `fief-run_default`.
```
docker run -it --network fief-run_default --name py-client --rm -p 8011:8011 -v $(pwd):/app python:3.11.4 /bin/bash
```

Once in the container, I manually run the python Getting Started file (as I did when I was configured to use Fief Cloud).
```
cd /app; python manual_token.py
```

```
# manual_token.py

from fief_client import Fief

fief = Fief(
    "http://fief-traefik",   # Docker Compose Container name that is available within the Docker Compose Network
    "<client id>", 
    "<client secret>"
)

redirect_url = "http://fief.localhost/docs/oauth2-redirect"

auth_url = fief.auth_url(redirect_url, scope=["openid"])
print(f"Open this URL in your browser: {auth_url}")

code = input("Paste the callback code: ")

tokens, userinfo = fief.auth_callback(code, redirect_url)
print(f"Tokens: {tokens}")
print(f"Userinfo: {userinfo}")
```

The error message I get when I run this is:
```
root@77aacd8816f0:/app# python manual_tokens.py
Traceback (most recent call last):
  File "/app/manual_tokens.py", line 11, in <module>
    auth_url = fief.auth_url(redirect_url, scope=["openid"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fief_client/client.py", line 529, in auth_url
    openid_configuration = self._get_openid_configuration()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fief_client/client.py", line 866, in _get_openid_configuration
    json = response.json()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

My guess is that I'm not using Traefik as Gabriel was intending it to be used in his original post.  I've been messing with this for a couple of days and I've run out of ideas.  As I mentioned previously, if I replace the Fief Server URL with the Fief Cloud url that I created, I am able to manually use the Python script to get an Access Token. 

 I'm pretty new to Traefik, so my guess is that I'm missing some essential configuration settings to get Traefik to operate the way I would like it to.  In Gabriel's example, he kind of shows how to set up a Uvicorn server for FastAPI and uses some settings that are likely the key to getting it to work with FastAPI.  So, it's possible that what I'm trying to do may not be possible with the local Dockerized Fief. 
```
   api:
      <<: *backend
      command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
      extra_hosts: # HERE 
        - "fief.localhost:host-gateway"  
```

I've also tried Ngrok, but that also failed in the fief_client code when Ngrok sent a 307 - Temporary Redirect and Fief did not detect the redirect and did nothing with it. 

Any ideas would be appreciated.  Ultimately, I want to get the FastAPI server up and running, but I thought if I couldn't get the simple Python script to manually authenticate, I'm not going to be able to get the FastAPI server running.  (And without the complete example from Gabriel, I didn't want to jump into that until I understood this.)

**Comment by fief-bailiff** [comment]
Hail, @ScottFred 👋 Welcome to Fief's kingdom!

Our team will get back to you very soon to help.

In the meantime, take a minute to star our repository ⭐️

![star-fief](https://user-images.githubusercontent.com/1144727/192523552-dc2c31fa-ae94-42fa-9ab4-7d0ba51bb7b0.png)

Farewell!

**Comment by gabrielcnegre** [comment]
Hey @ScottFred,

I just answered your response on my original post and will do my best to help you.

You are missing some key points of my solution, also, everything I omitted from my code was irrelevant to the solution at hand. Although, I now see how it could be confusing if you're new to Docker/FastAPI (apologies for that).

But I have to say, It's odd you thought the answer was in the bits I cut, rather than what I actually showed. 

Anyway, let's dive in:

### First, let's clear up some Docker stuff:

- If you're using Compose, you don't need to create the containers/networks manually. Just run `docker-compose up` to run everything, `docker-compose up app` to run only the app service along with its dependencies, `docker-compose run --rm app bash` to run bash inside a container of the app service (similar to `up app`, but this creates another container and does not expose ports and some other things), or `docker-compose exec -it app bash` to run bash inside the running app service.

- Be careful not to mix up container name and service name. Docker Compose will perform DNS resolution for services in the same network, allowing you to reference another service host by its name. For example, if you wanted to access port 8000 of your Fief server named "server" from another server, you would call "server:8000". The container name is irrelevant here.

### Now, let's talk about Traefik/networking with Docker:

- Traefik is a reverse proxy, easily integrated with Docker. It connects to the Docker socket and intercepts ingress traffic. You define routers in the service's labels, which tells Traefik, "Hey, if someone asks for X, pass it to me!" In your case, you defined a router in the Fief server service that routes when the host is `fief.localhost`; you also said this router will receive traffic from the entrypoint 'web', and the port of the service handling the request is 8000.

```yaml
server: # This is the service name
    <<: *fief-environment
    container_name: fief-server # Not needed
    image: ghcr.io/fief-dev/fief:0.27.0
    command: fief run-server --port 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fief.rule=Host(`fief.localhost`)"
      - "traefik.http.routers.fief.entrypoints=web"
      - "traefik.http.services.fief.loadbalancer.server.port=8000"
    expose:
      - 8000
```

### What does it mean for a router's entrypoint to be 'web'? 
It means that this router will listen for the entrypoint named 'web' you defined in your Traefik service's command:

```yaml
traefik:
    image: traefik:v2.4
    container_name: fief-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080  # For Traefik's dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

You also said that web's port is 80, meaning all ingress traffic to localhost:80 will be funneled to this entrypoint and consequently to routers with it as their entrypoint. 

(as a sidenote, port 8080 is for Traefik's dashboard)

- The following (code you showed) is incorrect on three levels:

```python
fief = Fief(
    "http://fief-traefik",
    "<client id>", 
    "<client secret>"
)
```

1. It should be the service's name, not the container's name.
2. From your service's perspective, the Fief server would be "server:8000" (but this wouldn't work for Fief due to the reason below).
3. This is the crux of my solution: setting your Fief's URL to "server:8000" would enable your Python service to communicate with it, but the keys returned would be relative to a machine called "server", which your host machine wouldn't recognize.

### Why does my solution exist?

Consider you have a Fief server service called 'fief', exposing port 8000.

The Fief client requests server configuration from inside the FastAPI service, typically "fief:8000". This means the keys are authenticated for a host called "fief:8000". Typing "fief:8000" in your browser wouldn't resolve, because your host machine doesn't recognize it.

**The challenge of running Fief locally with other services is that Fief's server must be accessible by both the client on the FastAPI server and the end user of the token via the same address.**

My solution:

Define a hostname accessible from both the service network and your host network.

1. Configure Traefik to route "fief.localhost" to the service 'fief':

```yaml
fief:
    ...
    labels: 
        - "traefik.enable=true" 
        - "traefik.http.routers.api.rule=Host(`fief.localhost`)"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
    ...
```

2. Ensure other services requesting "fief.localhost" are directed through localhost:

```yaml
fastapi:
    ...
    extra_hosts: 
        - "fief.localhost:host-gateway" 
    ...
```

Configure the client like this:

```python
oauth2 = OAuth2AuthorizationCodeBearer(
    f"{settings.fief_server_url}/authorize",
    f"{settings.fief_server_url}/api/token",
    scopes={"openid": "openid", "offline_access": "offline_access"},
    auto_error=False,
)
```

Now, both your service and you as a user see Fief from "http://fief.localhost". For both, this routes to localhost. Traefik, recognizing the subdomain "fief.localhost", routes the request to the router configured for "fief.localhost", which is Fief's server.

(from within fastapi server) fief.localhost:80 -> host-gateway -> localhost:80 -> web entrypoint -> fief:8000 
(from your browser) fief.localhost:80 -> localhost:80 -> web entrypoint -> fief:8000 

On a personal note, I appreciate the feedback and will improve next time. However, it felt a bit like I brought cake for the team, and the first thing I heard was: "Nice, but if you wanna bring cake, first check if anyone has cake related problems" I understand the sentiment, but it felt somewhat dismissive of the effort. It's like, I get it, but it seems you are focusing on what is missing and not on what you have.

Alas, I recognize there's room for improvement and am open to learning.

If there's anything else I can help you with, feel free to ask. I'll respond as soon as possible.

Cheers,
Gabriel

**Comment by ScottFred** [comment]
@gabrielcnegre  Thanks for the detailed response.  I hope we can help each other learn a little more as we go.  I didn't mean to seem dismissive of your effort; I'm just trying to help you understand that to knock it out of the park, having a complete example that can simply copied and run is where the true value comes from.  Think of it like posting something on StackOverflow and people giving you feedback not only on your solution, but how you communicated it (up vote / down vote).

One thing I might be able to help you with is your use of `docker-compose`; this is the old V1 script reference.  So, when you are writing on the internet, people will assume you're using an old version of Docker Compose when you do that.  I'll assume you're using the newer version Docker Compose V2 with some kind of alias...?

> Just run docker-compose up to run everything, docker-compose up app to run only the app service along with its dependencies,

If you are using Docker Compose V2, you should be using `docker compose` without the `-`(dash).  Here's [the official documentation](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose) about it.  I realize that depending on what system you're using, `docker-compose` could be aliased to `docker compose`, but to avoid confusion to your audience, you should use the newer version to communicate that you are using V2. 

> Now, let's talk about Traefik/networking with Docker:

Yeah, this is the good stuff....  First off, I wasn't aware of Docker Compose `labels:`.   At first glance I thought they were the same as [Docker Labels](https://docs.docker.com/config/labels-custom-metadata/) which are used to add Metadata to images, networks, volumes, etc; so I completely glossed over them!  I'll take a look at your other ideas and see if I can't get my version up and running.  And post it back here.  Thanks!

**Reply by ScottFred** [reply]
Okay, so those actually ARE nothing more than Docker Labels, but somehow Traefik is able to use them to perform static configuration when the Docker Containers are started.  Hmm... interesting.  For others stumbling on to this later:

You can find [explanation for the Traefik command line options](https://doc.traefik.io/traefik/reference/static-configuration/cli/) that are used with the Traefik Docker Compose `command:`.  In my opinion the Traefik  options are not intuitive.  For example, it's not intuitive that `--entrypoints.web.address` is actually naming the entrypoint "web" and assigning it port 80.  In other words, we could have used `--entrypoints.scott.address` and the rest of the configuration would then refer to "scott" as being the entrypoint name associated with port 80.

```
   traefik:
      image: traefik:v2.4
      container_name: fief-traefik
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
```

There is a [simple docker-compose.yml example](https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/):

**Reply by gabrielcnegre** [reply]
Hey @ScottFred,

You are absolutely right. I need to think about these sorts of things when I post something here. Next time, I will do it better. Providing a reproducible example is certainly the best way to do it. It just shows my lack of experience in doing this sort of things.

Regarding Docker Compose, I am using v3 (docker compose instead of docker-compose, I didn't think about it on my answer), but the point was that I saw you created the containers manually and were running the app by first entering the container and running it from inside, which is not wrong but surely not the easiest way to use it. I definitely should have done the comment referencing thing and added a note about Docker Compose.

On Traefik, yes, the way you configure it is really weird at first glance. You can actually do it using a separate YAML/TOML, but in the end, using the labels is very simple. Nowadays, I really prefer Traefik over Nginx because of its integration with Docker, Compose, and Swarm.

Again, I really do appretiate the feedback, and hope you get your project up and running. 

I need to start giving back to the open source community, and will do a better job next time.

**Reply by ScottFred** [reply]
@gabrielcnegre  

> , but the point was that I saw you created the containers manually and were running the app by first entering the container and running it from inside, which is not wrong but surely not the easiest way to use it.

Sorry for the confusion, I didn't create the containerS manually.  I only created One of the containers manually because it is not a continuously running process, but [a simple Python program](https://docs.fief.dev/integrate/python/) that is used to demonstrate the OAuth flow process and requires interactivity. I'm not aware of a way to use Docker Compose to be able to start an interactive CLI process.  But, I guess I could have created a python Compose Service and specified that the `command: /bin/bash` and then used `docker exec -it ...` into it.  So, that's why I ran the Docker Container manually and attached it to the Docker Network.

I think you meant Compose V2... [the newest version of Docker Compose is 2.23.1](https://docs.docker.com/compose/release-notes/) which you can find by running `docker compose version`.  This can be confusing because the docker-compose.yml file used to require a `version: #` which is currently somewhere in the 3.# range, but that is now optional and it is not kept in sync with the Docker Compose version.  This is not the version I was referring to since it's optional, it's rarely used.

Thanks again for your "Tutorial"!  It's taught me a lot about Traefik.

**Comment by frankie567** [comment]
Hello there 👋 

Thank you @ScottFred and @gabrielcnegre for the rich exchange regarding Docker and Traefik. 

I think configuring a Traefik application is really interesting for production deployment, however, this may be a bit complex for starting during development.

I've just released a [new version of the Python client](https://github.com/fief-dev/fief-python/releases/tag/v0.18.2) which should help with this use-case of working inside Docker networking. Here is how you can use it:

Considering Fief domain is configured as follows:

```.env
PORT=8000
ROOT_DOMAIN=localhost:8000
FIEF_DOMAIN=localhost:8000
```

You can configure the Python client like this:

```py
fief = FiefAsync(  
    "http://fief-server:8000",  # This is the host *internal* to Docker
    "YOUR_CLIENT_ID",
    "YOUR_CLIENT_SECRET",
    host="localhost:8000"  # This is the *outside* host whose Fief is configured on
)
```

So, the key point here is to **configure Fief normally so it works on your local machine** (i.e. with a `localhost` hostname).

However, when using the client, you should use the internal Docker host, so your app container can reach Fief's container. The trick is to set the optional `host` argument to the "real" Fief hostname so Fief server can recognize the workspace.

Let me know what you think about it! If it works well, I'll add it in more details to the documentation.

**Reply by gabrielcnegre** [reply]
If it works, it's definitely better!

To be honest, I got the Traefik idea because I was already using it in production. And since the Compose configuration is so simple (especially compared to Nginx/Apache configurations), it fit like a glove.

One thing I will mention is that I remember the host option already existing in the Fief Python client. This was the first thing I actually tried, along with ngrok and a bunch of other things. I'm guessing it's working differently now.

Anyway, thanks for Fief @frankie567!

Hope I can help with the project

**Reply by ScottFred** [reply]
@frankie567  I'm grabbing the new version of the Python Client today and I'll report back later today.  Thanks for writing Fief and creating a great software product.  I really like VS Code Devcontainers; I write all of my code in Devcontainers, so having that available with Fief was a great surprise.

**Comment by ScottFred** [comment]
@frankie567   Thanks again for creating a new version of the Python Client.  I got it installed, updated my Docker Compose files, but I'm still running into a strange error.  I'll give you the results of what I'm seeing first and then show you how I got them in case you want to try to recreate it.

When I try to run the Python Client code to manually go through the OAuth flow, my Python execution produces the following Error Stack:
```
appuser@e7bad2c29852:/app$ python manual_tokens.py
Traceback (most recent call last):
  File "/app/manual_tokens.py", line 12, in <module>
    auth_url = fief.auth_url(redirect_url, scope=["openid"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fief_client/client.py", line 542, in auth_url
    return self._auth_url(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fief_client/client.py", line 287, in _auth_url
    authorization_endpoint = self._get_endpoint_url(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fief_client/client.py", line 250, in _get_endpoint_url
    splitted_url = urlsplit(openid_configuration[field])
                            ~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'authorization_endpoint'
```

This error message suggested to me that something is wrong in the /.well-known/openid-connection call, so I looked into the Fief Server log messages and I see the HTTP status. code 400:  
```
fief-server | 2023-11-20 19:06:45.129 | INFO     | uvicorn.protocols.http.httptools_impl:send:496 - 192.168.192.6:37304 - "GET /.well-known/openid-configuration HTTP/1.1" 400 - {}
```

So, then I tried to just execute this from my browser to see what I would get:  `http://localhost:8000/.well-known/openid-connection` and I it works from the browser just a few seconds later.
```
fief-server  | 2023-11-20 19:10:46.779 | INFO     | uvicorn.protocols.http.httptools_impl:send:496 - 192.168.192.1:59402 - "GET /.well-known/openid-configuration HTTP/1.1" 200 - {}
```

And the browser displays the following; nothing in here jumps out to me in here that looks wrong:
```
{"issuer":"https://localhost:8000","authorization_endpoint":"http://localhost:8000/authorize","token_endpoint":"http://localhost:8000/api/token","jwks_uri":"http://localhost:8000/.well-known/jwks.json","registration_endpoint":"http://localhost:8000/register","scopes_supported":["openid","offline_access"],"response_types_supported":["code","code id_token","code token","code id_token token"],"response_modes_supported":["query","fragment"],"grant_types_supported":["authorization_code","refresh_token"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"service_documentation":"https://docs.fief.dev","code_challenge_methods_supported":["plain","S256"],"userinfo_endpoint":"http://localhost:8000/api/userinfo","acr_values_supported":["0","1"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["RS256"],"id_token_encryption_alg_values_supported":["RSA-OAEP-256"],"id_token_encryption_enc_values_supported":["A256CBC-HS512"],"userinfo_signing_alg_values_supported":["none"],"claims_supported":["email","email_verified","is_active","tenant_id","fields"],"request_parameter_supported":false}
```

So, here are the steps I used, in case you want to re-create it or review:
docker-compose.yml:
```
x-fief:
  &fief-environment
  # technically, if all keys in the .env file are the same as the environment variable
  #   being read, this would not be necessary
  environment:
    - SECRET=${FIEF_SECRET}
    - FIEF_CLIENT_ID=${FIEF_CLIENT_ID}
    - FIEF_CLIENT_SECRET=${FIEF_CLIENT_SECRET}
    - ENCRYPTION_KEY=${FIEF_ENCRYPTION_KEY}
    - PORT=${PORT}
    - ROOT_DOMAIN=${FIEF_ROOT_DOMAIN}
    - FIEF_DOMAIN=${FIEF_DOMAIN}
    - FIEF_MAIN_USER_EMAIL=${FIEF_MAIN_USER_EMAIL}
    - FIEF_MAIN_USER_PASSWORD=${FIEF_MAIN_USER_PASSWORD}
    - DATABASE_TYPE=${DATABASE_TYPE}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_USERNAME=${DATABASE_USERNAME}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}
    - REDIS_URL=${REDIS_URL}
  depends_on:
    - db
    - redis

services:
   db:
      container_name: fief-db
      image: postgres:16.1-alpine
      ports:
        - 5432:5432
      env_file: # technically not necessary because default .env is used
        - .env
      volumes:
        - fief-postgres-data:/var/lib/postgresql/data

   redis:
      container_name: fief-redis
      image: redis:alpine
      command: redis-server --save 60 1 --loglevel warning
      volumes:
        - fief-redis-data:/data

   fief:
      <<: *fief-environment
      container_name: fief-server
      image: ghcr.io/fief-dev/fief:0.27.0
      command: fief run-server --port 8000
      ports:
        - 8000:8000

   worker:
      <<: *fief-environment
      container_name: fief-worker
      image: ghcr.io/fief-dev/fief:0.27.0
      command: fief run-worker -p 1 -t 1

volumes:
  fief-redis-data:
  fief-postgres-data:
```

.env:
```
# Reference: https://docs.fief.dev/self-hosting/environment-variables/

# Fief Secrets
FIEF_SECRET=aaaaaa
FIEF_CLIENT_ID=bbbbbb
FIEF_CLIENT_SECRET=cccccc
FIEF_ENCRYPTION_KEY=ddddd
PORT=8000
FIEF_ROOT_DOMAIN=localhost:8000
FIEF_DOMAIN=localhost:8000
FIEF_MAIN_USER_EMAIL=scott@<email>com
FIEF_MAIN_USER_PASSWORD=eeeeee
FIEF_SERVER_URL=http://localhost:8000

# Read more: https://docs.fief.dev/self-hosting/deployment/setup-database/
DATABASE_TYPE=POSTGRESQL
DATABASE_HOST=fief-db
DATABASE_PORT=5432
DATABASE_USERNAME=fief
DATABASE_PASSWORD=fffffffff
DATABASE_NAME=fief

REDIS_URL=redis://fief-redis:6379
```

Using the code from the Simple Python Client to do manual OAuth Authentication: `manual_tokens.py`
```
from fief_client import Fief

fief = Fief(
    "http://fief-server:8000",
    "CLIENT_ID",
    "CLIENT_SECRET",
    host="http://localhost:8000"
)

redirect_url = "http://localhost:8000/callback"

auth_url = fief.auth_url(redirect_url, scope=["openid"])     <-- This is the line that fails
print(f"Open this URL in your browser: {auth_url}")

code = input("Paste the callback code: ")

tokens, userinfo = fief.auth_callback(code, redirect_url)
print(f"Tokens: {tokens}")
print(f"Userinfo: {userinfo}")
```

Docker Image build:
```
docker build -t fief-simple-python -f simple-python-Dockerfile .
```

Docker run:
```
docker run -it --network fief-run_default --name py-client --rm -p 8011:8011 -v $(pwd):/app fief-simple-python /bin/bash
```

Once in the container, I execute the script:  `python manual-tokens.py` and get the Python stack trace I shared above.

Since I can use this same process with the Fief Cloud account I created, I think it should work locally if I understand the changes you made to the Python Client to support "localhost" within Docker Networking.  Any thoughts?
