### DISCUSSION TITLE
Docker I am encountering the error [Errno -2] Name or service not known

### DISCUSSION THREAD

**Discussion by mneriklick** [fief-dev/fief#353] [Q&A] [answered]
I am encountering the error [Errno -2] Name or service not known when I attempt to start the server on Docker. Below is a snippet of the log error:
`fief run-server --host 0.0.0.0:8080`

Log:
```
# fief run-server --host 0.0.0.0:8080
/usr/local/lib/python3.12/site-packages/pydantic_settings/sources.py:376: UserWarning: directory "/run/secrets" does not exist
  warnings.warn(f'directory "{self.secrets_path}" does not exist')
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Admin already exists
Admin API key not provided in settings. Skipping its creation.
INFO:     Started server process [301]
INFO:     Waiting for application startup.
2024-03-18 17:24:56.752 | INFO     | fief.lifespan:lifespan:25 - Fief Server started - {"version": "0.28.5"}
2024-03-18 17:24:56.753 | WARNING  | fief.lifespan:lifespan:28 - Telemetry is enabled.
We will collect data to better understand how Fief is used and improve the project.
You can opt-out by setting the environment variable `TELEMETRY_ENABLED=false`.
Read more about Fief's telemetry here: https://docs.fief.dev/telemetry - {}
[Errno -2] Name or service not known
2024-03-18 17:24:56.763 | INFO     | fief.lifespan:lifespan:43 - Fief Server stopped - {}
# 
```
I have verified the network connectivity between the Postgers, Redis, Server, and Worker servers. All servers are on the same network and can ping each other by name and IP address without any issues.

I am unsure if there is a way to start the server in verbose or debug mode to gain a better understanding of the error. Any suggestions on how to approach this would be greatly appreciated.

Here is my Docker Compose file:
```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - redis
      - service1
      - service2
      - service3
    networks:
      - mynetwork
  service1:
    build: ./microservice1
    image: service1_image
    container_name: service1
    volumes:
      - ./microservice1:/app
      - ./certs:/certs
    working_dir: /app
    #command: bash -c "pip install -r requirements.txt && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT_SERVICE1} -m uvicorn app:app --host 0.0.0.0 --port ${APP_PORT_SERVICE1} --reload --ssl-keyfile=/certs/key.pem --ssl-certfile=/certs/cert.pem"
    command: bash -c "pip install -r requirements.txt && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT_SERVICE1} -m uvicorn app:app --host 0.0.0.0 --port ${APP_PORT_SERVICE1} --reload"
    ports:
      - "${APP_PORT_SERVICE1}:${APP_PORT_SERVICE1}"
      - "${DEBUG_PORT_SERVICE1}:${DEBUG_PORT_SERVICE1}"
    depends_on:
      - redis
    environment:
      DATABASE_USER: microservice1
      DATABASE_SCHEMA: microservice1
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      APPMARJOR: ${APPMARJOR_SERVICE1}
      APPMINOR: ${APPMINOR_SERVICE1}
    networks:
      - mynetwork

  service2:
    build: ./microservice2
    image: service2_image
    container_name: service2
    volumes:
      - ./microservice2:/app
      - ./certs:/certs
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT_SERVICE2} -m uvicorn app:app --host 0.0.0.0 --port ${APP_PORT_SERVICE2} --reload"
    ports:
      - "${APP_PORT_SERVICE2}:${APP_PORT_SERVICE2}"
      - "${DEBUG_PORT_SERVICE2}:${DEBUG_PORT_SERVICE2}"
    depends_on:
      - redis
    environment:
      DATABASE_USER: microservice2
      DATABASE_SCHEMA: microservice2
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      APPMARJOR: ${APPMARJOR_SERVICE2}
      APPMINOR: ${APPMINOR_SERVICE2}
    networks:
      - mynetwork

  service3:
    build: ./microservice3
    image: service3_image
    container_name: service3
    volumes:
      - ./microservice3:/app
      - ./certs:/certs
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python -m debugpy --listen 0.0.0.0:${DEBUG_PORT_SERVICE3} -m uvicorn app:app --host 0.0.0.0 --port ${APP_PORT_SERVICE3} --reload"
    ports:
      - "${APP_PORT_SERVICE3}:${APP_PORT_SERVICE3}"
      - "${DEBUG_PORT_SERVICE3}:${DEBUG_PORT_SERVICE3}"
    depends_on:
      - redis
    environment:
      DATABASE_USER: microservice3
      DATABASE_SCHEMA: microservice3
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      APPMARJOR: ${APPMARJOR_SERVICE3}
      APPMINOR: ${APPMINOR_SERVICE3}
    networks:
      - mynetwork

  fief-server:
    image: ghcr.io/fief-dev/fief:latest
    #command: fief run-server --host 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - .env.development
    environment:
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - redis
    networks:
      - mynetwork

  fief-worker:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-worker -p 1 -t 1
    env_file:
      - .env.development
    environment:
      - "REDIS_URL=redis://redis:6379"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork


# Define any networks or volumes shared between services
networks:
  mynetwork:
    driver: bridge
    external: true

volumes:
  shared_data:
  redis-data:

```
