### DISCUSSION TITLE
localhost vs 127.0.0.1 in docker-compose

### DISCUSSION THREAD

**Discussion by jinserk** [fief-dev/fief#37] [Q&A]
Hi,

I have a project with `fastapi` and `fief` altogether in docker-compose as different containers (named `api` and `fief` respectively), serving them in the exposed ports 8001 and 8002 respectively. I followed the instruction described in [here](https://docs.fief.dev/integrate/python/fastapi/) and checked the auth successful in http://localhost:8001/docs . However, when I try `/user` GET api, I've got an error that it have tried to connect 127.0.0.1:8002 -- which is `fief` api calls. I gave the args of `FiefAsyc` as:
```
fief = FiefAsync(
    "http://localhost:8002",
    "YOUR_CLIENT_ID",
    "YOUR_CLIENT_SECRET",
)
```
but it looks like `fastapi` or `auth = FiefAuth(fief, scheme)` changed the `localhost` to `127.0.0.1`. This prevents the url to go to the container `fief` via host, but redirect back to the `api` container itself inside the docker compose env. Of course I set the env vars listed in [here](https://docs.fief.dev/self-hosting/environment-variables/#using-docker-compose). Do you have any idea how to resolve this?

**Comment by frankie567** [comment]
Hi @jinserk 👋 

Could you share your docker-compose configuration and the error you're getting? That would help debug the issue :)

I think the problems comes from the fact that `api` container tries to call the `fief` container through `localhost`. But in a Docker context, you should probably call it through the `fief` host:

```py
fief = FiefAsync(
    "http://fief:8002",
    "YOUR_CLIENT_ID",
    "YOUR_CLIENT_SECRET",
)
```

But I fear that'll break the redirection when trying to authenticate through  your local machine 🤔

**Reply by jinserk** [reply]
Thank you @frankie567 . I tried `fief` instead of `localhost` at the first, but in the case I cannot make the authentication work in docs since it's base url is `fief:8002` as follows:
![image](https://user-images.githubusercontent.com/823222/174443217-2ffaacba-a9fd-402c-8cc4-24c96cc6f34f.png)
As you can image, the host browser doesn't know `fief:8002` outside the docker-compose env. 

Here is my `docker-compose.yml`:
```yaml
version: '3'                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                               
services:                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                               
  backend:                                                                                                                                                                                                                                                                     
    build: ${JHEE_SALE_PATH}/backend                                                                                                                                                                                                                                           
    command: uvicorn api.main:app --reload --workers 1 --host 0.0.0.0 --port 8001                                                                                                                                                                                              
    volumes:
      - ./backend:${APP_DIR}:rw
    ports:
      - 8001:8001
    environment:
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=jhee_sale
    depends_on:
      - db
    working_dir: ${APP_DIR}

  fief:
    image: ghcr.io/fief-dev/fief:latest
    ports:
      - 8002:8002
    environment:
      - SECRET=-xxx
      - FIEF_CLIENT_ID=XXX
      - FIEF_CLIENT_SECRET=XXX
      - ENCRYPTION_KEY=XXX
      - PORT=8002
      - ROOT_DOMAIN=localhost:8002
      - FIEF_DOMAIN=localhost:8002
      - CSRF_COOKIE_SECURE=False
      - LOGIN_SESSION_COOKIE_SECURE=False
      - SESSION_COOKIE_SECURE=False
      - FIEF_ADMIN_SESSION_COOKIE_SECURE=False
      - DATABASE_TYPE=POSTGRESQL
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fief
    depends_on:
      - db

       
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jhee_sale
    volumes:
      - localdb:/var/lib/postgresql/data

volumes:
  localdb:
    driver: local
```
