### DISCUSSION TITLE
help getting started

### DISCUSSION THREAD

**Discussion by andyseubert** [fief-dev/fief#528] [Q&A]
I am self-hosting Fief, or want to..
when I attempt to login to the admin portal, it just sits there. It does reload the page, but it does not go to the portal. The password reset seems to work in that it sends an email and lets me enter a new password. 
when I put in the wrong password, it tells me it is wrong.
so every thing _seems_ to be working except I cannot get into the admin portal!

and there are no errors in the logs.

any suggestions?
Thanks!

I have the docker configuration here
```
services:
  fief-server:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-server
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  fief-worker:
    image: ghcr.io/fief-dev/fief:latest
    command: fief run-worker -p 1 -t 1
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=*********
      - POSTGRES_USER=****
      - POSTGRES_DB=fief
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  postgres-data:
```
### my .env looks like
```
# Reference: https://docs.fief.dev/self-hosting/environment-variables/

SECRET=********
FIEF_CLIENT_ID=XXX
FIEF_CLIENT_SECRET=********
ENCRYPTION_KEY=********

PORT=8000
# Set your domain name here
FIEF_DOMAIN=fief.ki7pli.com
# Set your email address here
FIEF_MAIN_USER_EMAIL=andys@ki7pli.com
FIEF_MAIN_USER_PASSWORD=********

# Read more: https://docs.fief.dev/self-hosting/configuration/database/
DATABASE_TYPE=POSTGRESQL
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USERNAME=fief
DATABASE_PASSWORD=********
DATABASE_NAME=fief

# Read more: https://docs.fief.dev/self-hosting/environment-variables/#redis
REDIS_URL=redis://redis:6379

# Read more: https://docs.fief.dev/self-hosting/configuration/ssl/
FORWARDED_ALLOW_IPS=192.168.68.*,127.0.0.1

EMAIL_PROVIDER=SENDGRID
EMAIL_PROVIDER_PARAMS={"api_key": "********"}
DEFAULT_FROM_EMAIL="andys@ki7pli.com"
DEFAULT_FROM_NAME="test"
```
### I am using apache httpd to be the reverse proxy
```
<VirtualHost *:80>
    ServerName fief.ki7pli.com

    # If you want to automatically redirect HTTP to HTTPS:
    RewriteEngine On
    RewriteCond %{SERVER_NAME} =fief.ki7pli.com
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=301]
RewriteCond %{SERVER_NAME} =fief.ki7pli.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName  fief.ki7pli.com

    # Proxy configuration
    ProxyPreserveHost On
    ProxyRequests Off
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/
    
    # Allow WebSocket upgrade (if needed by Fief, or for future usage)
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule .* "ws://127.0.0.1:8000/$1" [P,L]
SSLCertificateFile /etc/letsencrypt/live/fief.ki7pli.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/fief.ki7pli.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```
